apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "21"
  name: default
  namespace: istio-system
spec:
  members:
    # a list of projects joined into the service mesh
    - psychdocs