title: "ADR - [TITLE_GOES_HERE]"
labels: ["ADR"]
body:
  - type: markdown
    attributes:
      value: |
        Let's capture an important architecture decision made along with discussion.

  - type: textarea
    id: context
    attributes:
      label: Details
      description: "Describe here the forces that influence the design decision, including technological, cost-related, and project local."
      value: |

  - type: textarea
    id: decision
    attributes:
      label: Decision
      description: "Describe here our response to these forces, that is, the design decision that was made. State the decision in full sentences, with active voice (We will...)."
      value: |

  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: "Describe here the rationale for the design decision. Also indicate the rationale for significant *rejected* alternatives. This section may also indicate assumptions, constraints, requirements, and results of evaluations and experiments."
      value: |

  - type: textarea
    id: consequences
    attributes:
      label: Consequences
      description: "Describe here the resulting context, after applying the decision. All consequences should be listed, not just the positive ones."
      value: |

  - type: dropdown
    id: status
    attributes:
      label: Choose status below. If deprecated, indicate why. If superseded, include a link to the new ADR
      options:
        - Proposed
        - Accepted
        - Deprecated
        - Superseded
    validations:
      required: true

  - type: input
    id: authors
    attributes:
      label: Authors
      description: _at_ anyone involved in the decision
    validations:
      required: true