apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  argocd.argoproj.io/sync-wave: 30"
  name: psychdocs-realm
spec:
  keycloakCRName: psychdocs-keycloak
  realm:
    id: psychdocs-realm
    realm: epsychdocs-realm
    displayName: PsychdocsRealm
    enabled: true