apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  name: psychdocs-keycloak
  namespace: psychdocs
  labels:
    app: sso
spec:
  instances: 1
  externalAccess:
    enabled: True