apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: psychdocs-keycloakrealm
  namespace: psychdocs
spec:
  instanceSelector:
    matchLabels:
      app: sso
  realm:
    displayName: Psychdocs Realm
    enabled: true
    id: basic
    realm: basic